# Generated by Django 6.1 on 2026-08-24 12:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Achievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField(blank=True)),
                ("date", models.DateField(blank=True, null=True)),
                ("icon", models.CharField(blank=True, default="🏆", max_length=50)),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["order", "-date"],
            },
        ),
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("CODING", "Coding Activity"),
                            ("LEARNING", "Learning Activity"),
                            ("CAREER", "Career Activity"),
                        ],
                        max_length=10,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("icon", models.CharField(blank=True, default="📌", max_length=50)),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Activities",
                "ordering": ["order", "-date"],
            },
        ),
        migrations.CreateModel(
            name="Certification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("organization", models.CharField(max_length=300)),
                ("description", models.TextField(blank=True)),
                (
                    "skills",
                    models.TextField(
                        blank=True, help_text="Key skills covered, one per line"
                    ),
                ),
                (
                    "certificate_image",
                    models.ImageField(blank=True, null=True, upload_to="certificates/"),
                ),
                (
                    "certificate_pdf",
                    models.FileField(blank=True, null=True, upload_to="certificates/"),
                ),
                (
                    "verification_url",
                    models.URLField(
                        blank=True,
                        help_text="Official verification link (if available)",
                    ),
                ),
                ("date_earned", models.DateField(blank=True, null=True)),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("company", models.CharField(blank=True, max_length=200)),
                ("job_role", models.CharField(blank=True, max_length=200)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_read", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Contact Message",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "degree",
                    models.CharField(
                        help_text="e.g. Bachelor of Engineering – Information Technology",
                        max_length=200,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("BE", "Bachelor of Engineering"),
                            ("BSC", "Bachelor of Science"),
                            ("MSC", "Master of Science"),
                            ("ME", "Master of Engineering"),
                            ("HSC", "Higher Secondary Certificate"),
                            ("SSC", "Secondary School Certificate"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=10,
                    ),
                ),
                ("institution", models.CharField(max_length=300)),
                ("university", models.CharField(blank=True, max_length=300)),
                ("start_year", models.IntegerField(blank=True, null=True)),
                ("end_year", models.IntegerField(blank=True, null=True)),
                (
                    "cgpa",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                (
                    "percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="Display order (lower = first)"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Education",
                "ordering": ["order", "-end_year"],
            },
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="e.g. Data Science Intern", max_length=200
                    ),
                ),
                ("company", models.CharField(max_length=200)),
                ("location", models.CharField(blank=True, max_length=200)),
                ("start_date", models.DateField()),
                (
                    "end_date",
                    models.DateField(
                        blank=True, help_text="Leave blank if current", null=True
                    ),
                ),
                ("is_current", models.BooleanField(default=False)),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="General description of the role"
                    ),
                ),
                (
                    "responsibilities",
                    models.TextField(
                        blank=True, help_text="One responsibility per line"
                    ),
                ),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Experience",
                "ordering": ["order", "-start_date"],
            },
        ),
        migrations.CreateModel(
            name="GitHubCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.JSONField(default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "GitHub Cache",
                "verbose_name_plural": "GitHub Cache",
            },
        ),
        migrations.CreateModel(
            name="JobRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Recommended Job Role",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                (
                    "title",
                    models.CharField(
                        help_text="e.g. AI/ML Engineer | Data Scientist", max_length=200
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        help_text="Professional summary / about description"
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=200)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20)),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="profile/"),
                ),
                (
                    "resume_pdf",
                    models.FileField(blank=True, null=True, upload_to="resume/"),
                ),
                (
                    "professional_summary",
                    models.TextField(
                        blank=True,
                        help_text="Detailed professional summary for the resume section",
                    ),
                ),
            ],
            options={
                "verbose_name": "Profile",
                "verbose_name_plural": "Profile",
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("slug", models.SlugField(max_length=300, unique=True)),
                (
                    "short_description",
                    models.TextField(help_text="Brief description for project cards"),
                ),
                ("description", models.TextField(help_text="Full project description")),
                ("problem_statement", models.TextField(blank=True)),
                ("solution", models.TextField(blank=True)),
                ("architecture", models.TextField(blank=True)),
                (
                    "features",
                    models.TextField(blank=True, help_text="One feature per line"),
                ),
                (
                    "algorithm",
                    models.CharField(
                        blank=True, help_text="e.g. Logistic Regression", max_length=200
                    ),
                ),
                (
                    "dataset_info",
                    models.TextField(blank=True, help_text="Dataset description"),
                ),
                (
                    "results",
                    models.TextField(
                        blank=True, help_text="Results, accuracy, metrics"
                    ),
                ),
                ("challenges", models.TextField(blank=True)),
                ("future_improvements", models.TextField(blank=True)),
                ("github_url", models.URLField(blank=True)),
                ("live_demo_url", models.URLField(blank=True)),
                (
                    "screenshot",
                    models.ImageField(blank=True, null=True, upload_to="projects/"),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_title",
                    models.CharField(
                        default="Dhanaraj AI/ML Portfolio", max_length=200
                    ),
                ),
                (
                    "tagline",
                    models.CharField(
                        default="AI/ML Engineer | Data Scientist | Python Developer | Data Analyst",
                        max_length=300,
                    ),
                ),
                (
                    "secondary_tagline",
                    models.CharField(
                        default="My Skills, Projects, Experience, Certifications & Career Journey — All in One Place.",
                        max_length=500,
                    ),
                ),
                ("github_username", models.CharField(blank=True, max_length=100)),
                ("linkedin_url", models.URLField(blank=True)),
                (
                    "meta_description",
                    models.TextField(
                        default="Dhanaraj Arjun Lokhande — AI/ML Engineer & Data Scientist portfolio showcasing Python, Machine Learning, and Data Science projects.",
                        max_length=300,
                    ),
                ),
            ],
            options={
                "verbose_name": "Site Settings",
                "verbose_name_plural": "Site Settings",
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("PROGRAMMING", "Programming"),
                            ("LIBRARIES", "Python Libraries"),
                            ("ML", "Machine Learning"),
                            ("VISUALIZATION", "Visualization"),
                            ("TOOLS", "Developer Tools"),
                            ("SOFT", "Soft Skills"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "proficiency",
                    models.IntegerField(
                        default=70,
                        help_text="Proficiency level 1-100 (self-assessed, not a certification)",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True, help_text="CSS icon class or emoji", max_length=50
                    ),
                ),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["category", "order", "name"],
            },
        ),
        migrations.CreateModel(
            name="SocialLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("github", "GitHub"),
                            ("linkedin", "LinkedIn"),
                            ("email", "Email"),
                            ("twitter", "Twitter/X"),
                            ("portfolio", "Portfolio"),
                            ("kaggle", "Kaggle"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "url",
                    models.CharField(help_text="URL or email address", max_length=500),
                ),
                ("display_name", models.CharField(blank=True, max_length=200)),
                (
                    "icon_class",
                    models.CharField(
                        blank=True, help_text="CSS icon class", max_length=100
                    ),
                ),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Social Link",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ProjectTechnology",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("order", models.IntegerField(default=0)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="technologies",
                        to="core.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Technology",
                "verbose_name_plural": "Project Technologies",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ProjectWorkflowStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "icon",
                    models.CharField(
                        blank=True, help_text="CSS icon class or emoji", max_length=50
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflow_steps",
                        to="core.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Workflow Step",
                "ordering": ["order"],
            },
        ),
    ]
