# Generated by Django 6.1 on 2026-08-27 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoleResume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role_key",
                    models.CharField(
                        choices=[
                            ("data-analyst", "Data Analyst / Business Analyst"),
                            ("data-science", "Data Science / Data Scientist"),
                            ("machine-learning", "Machine Learning / AI Engineer"),
                            ("python-developer", "Python Developer"),
                            ("sql-developer", "SQL Developer / Database Analyst"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "summary",
                    models.TextField(
                        help_text="Tailored professional summary for this role"
                    ),
                ),
                ("key_skills", models.TextField(help_text="Comma-separated skills")),
                (
                    "resume_file",
                    models.FileField(blank=True, null=True, upload_to="resumes/roles/"),
                ),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Role Specific Resume",
                "verbose_name_plural": "Role Specific Resumes",
                "ordering": ["order", "title"],
            },
        ),
    ]
